### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by playnox** [ivyhjk/oauth2-phalcon#1]
Any chance you can post an example on how to make it running with Phalcon (Get access token, refresh token, revoke and etc...)

I'm trying to build stand-along oAuth2 server for multiple clients (apps)... 
Thank you!

**Comment by ivyhjk** [comment]
Hi, this version is currently in development mode, so, is not complete and has no documentation. BUT, i'm working in a new release for production based on the new release of "The PHP League" (https://github.com/thephpleague) 

regards

**Comment by RayHughes** [comment]
Interested in your project. When you finish the new version can you include the sql

**Comment by ivyhjk** [comment]
Added MySQL examples
